mixed-port: 7890
#socks-port: 7890
#port: 7890
ipv6: false
mode: rule
log-level: debug
global-client-fingerprint: chrome

keep-alive-interval: 15

allow-lan: false
bind-address: '0.0.0.0'

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

geo-auto-update: true
geo-update-interval: 24

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443]

dns:
  enable: true
  listen: 127.0.0.1:53
  ipv6: false
  use-hosts: true
  # enhanced-mode: redir-host
  nameserver-policy:
    '*.intra.*.*': '192.168.1.4'
    'geosite:cn':
      - https://1.12.12.12/dns-query
      - https://223.5.5.5/dns-query
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - 1.1.1.1
    - 8.8.4.4
    #- 'tls://1.1.1.1:853'
    #- https://doh.pub/dns-query
    - https://1.0.0.1/dns-query

proxies:

  - name: "PROXY"
    type: socks5
    server: 127.0.0.1
    port: 9999

rule-providers:
#  reject:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
#    path: ./ruleset/reject.yaml
#    interval: 86400
#
#  icloud:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
#    path: ./ruleset/icloud.yaml
#    interval: 86400
#
#  apple:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
#    path: ./ruleset/apple.yaml
#    interval: 86400
#
#  google:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
#    path: ./ruleset/google.yaml
#    interval: 86400
#
#  proxy:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
#    path: ./ruleset/proxy.yaml
#    interval: 86400
#
#  direct:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
#    path: ./ruleset/direct.yaml
#    interval: 86400
#
#  private:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
#    path: ./ruleset/private.yaml
#    interval: 86400
#
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

#
#  greatfire:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
#    path: ./ruleset/greatfire.yaml
#    interval: 86400
#
#  tld-not-cn:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
#    path: ./ruleset/tld-not-cn.yaml
#    interval: 86400
#
#  telegramcidr:
#    type: http
#    behavior: ipcidr
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
#    path: ./ruleset/telegramcidr.yaml
#    interval: 86400
#
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

#  cndomain:
#    behavior: domain
#    interval: 86400
#    path: ./ruleset/cn_domain.yaml
#    type: http
#    url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/cn_domain.yaml"

#  lancidr:
#    type: http
#    behavior: ipcidr
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
#    path: ./ruleset/lancidr.yaml
#    interval: 86400
#
#  applications:
#    type: http
#    behavior: classical
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
#    path: ./ruleset/applications.yaml
#    interval: 86400
#
rules:

#LAN
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT

#  - DOMAIN,introspector.oss-fuzz.com,DIRECT

#Bing
  - DOMAIN-SUFFIX,bing.com,PROXY

#OpenAi
  - DOMAIN-SUFFIX,openai.com,PROXY
  - DOMAIN-SUFFIX,chat.openai.com,PROXY
  - DOMAIN-SUFFIX,ai.com,PROXY
  - DOMAIN-SUFFIX,ifconfig.me,PROXY
  - DOMAIN-SUFFIX,challenges.cloudflare.com,PROXY
  - DOMAIN,cdn.auth0.com,PROXY
  - DOMAIN,challenges.cloudflare.com,PROXY
  - DOMAIN,openaiapi-site.azureedge.net,PROXY
  - DOMAIN-SUFFIX,identrust.com,PROXY

# Google
  - DOMAIN-SUFFIX,googlesyndication.com,PROXY
  - DOMAIN-SUFFIX,googleadservices.com,PROXY
  - DOMAIN-SUFFIX,translate.googleapis.com,PROXY

  - RULE-SET,gfw,PROXY

  - GEOIP,LAN,DIRECT


    # rule GEOSITE
  #- GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,google-cn,PROXY
  - GEOIP,google,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY

  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
    # source IPCIDR condition for all rules in gateway proxy
    #- GEOSITE,geolocation-!cn,REJECT,192.168.1.88/32,192.168.1.99/32

  #- GEOIP,telegram,PROXY,no-resolve
  #- GEOIP,private,DIRECT,no-resolve

  - MATCH,PROXY
